# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: NodePort # 외부에서 접속 가능한 NodePort 타입 사용
  selector:
    app: react-app # 'app: react-app' 레이블이 달린 Pod를 찾습니다.
  ports:
    - protocol: TCP
      port: 80 # 서비스 내부에서 사용할 포트
      targetPort: 80 # 컨테이너가 노출한 포트
      nodePort: 30001 # 클러스터 외부에서 접속할 포트
